openapi: 3.0.3

info:
  title: KC Web backend API
  description: Test project for API documentation and codegen
  version: 1.0.0
  contact:
    name: Andres Garcia
    email: andres-gr@users.noreply.github.com

servers:
  - url: http://localhost:4000/api/v1
    description: Testing v1 API

tags:
  - name: Users
    description: User management

  - name: Projects
    description: Project management

components:
  schemas:
    BaseResponse:
      type: string
      example: Response message

    Project:
      type: object
      required:
        - id
        - company
        - author
      properties:
        id:
          type: string
          example: 37014kdjasf01
        company:
          type: string
          example: Funahus LLC
        author:
          type: string
          example: John Smiff

    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          example: 1023kljlasdfja0
        name:
          type: string
          example: John Smiff
        email:
          type: string
          format: email
          description: Email of the user, is unique.
          example: jon@smiff.com

    GetUserResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        user:
          $ref: '#/components/schemas/User'

    GetProjectResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        project:
          $ref: '#/components/schemas/Project'

paths:
  /user:
    get:
      description: Get a random user info
      summary: Get a random user info
      tags:
        - Users
      responses:
        200:
          description: A random user object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'

  /project:
    get:
      description: Get a random project info
      summary: Get a random project info
      tags:
        - Projects
      responses:
        200:
          description: A random project object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetProjectResponse'
